# Generated by Django 4.2.20 on 2026-05-25 05:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.FileField(upload_to='receipts/')),
                ('merchant', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Medical', 'Medical'), ('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Other', max_length=40)),
                ('ocr_text', models.TextField(blank=True)),
                ('confidence_note', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
